'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import classNames from "classnames";
import { useState } from "react";
import { Bars3Icon, XMarkIcon } from "@heroicons/react/16/solid";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

const mobileLinkStyle = " text-lg font-semibold text-gray-600 p-2 w-fit";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showMobileMenu, setShowMobileMenu] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* mobile */}
        <div className="flex justify-end md:hidden" >
          {showMobileMenu 
           ? <XMarkIcon className="p-4 w-16 text-gray-600" onClick={() => setShowMobileMenu(!showMobileMenu)} />
           : <Bars3Icon className="p-4 w-16 text-gray-600" onClick={() => setShowMobileMenu(!showMobileMenu)} />
          }
          
          
        </div>
        <div className={classNames('flex justify-end m-4 md:hidden', !showMobileMenu && 'hidden')}>
          <nav className="flex flex-col items-center space-y-4 px-12 py-4 w-fit bg-white rounded shadow fixed z-10">
            <Link className={mobileLinkStyle} href="/">Hjem</Link>
            <Link className={mobileLinkStyle} href="/bilder">Bildegalleri</Link>
            <Link className={mobileLinkStyle} href="https://bryllupside.webflow.io/">Bryllupssiden</Link>
            <Link className={mobileLinkStyle} href="https://bryllupside.webflow.io/hold-date">Hold the date</Link>
          </nav>
        </div>
        {/* desktop */}
        <div className="md:flex justify-center mt-12 hidden">
          <nav className="flex px-12 py-4 bg-gray-500 text-white rounded-full shadow w-fit font-semibold">
            <Link href="/">Hjem</Link>
            <Link className="border-l-2 border-white ml-4 pl-4" href="/bilder">Bildegalleri</Link>
            <Link className="border-l-2 border-white ml-4 pl-4" href="https://bryllupside.webflow.io/">Bryllupssiden</Link>
            <Link className="border-l-2 border-white ml-4 pl-4" href="https://bryllupside.webflow.io/hold-date">Hold the date</Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
