export const thankYouParagraphs = [
  'Vi har gledes oss veldig mye til bryllupsdagen vår, og sett frem til å feire med dere!',
  'For oss var det viktig å ha bryllupet i nærheten av der de fleste av vår familie og venner bor. Vi overveiet bryllup i England, Frankrike og Italia, men til syvende og sist er det ingenting som slår en god feiring med hele familien, og hele vennegjengen. Vi har snakket mye om hva det vil si å gifte seg, når er det riktig å gifte seg, hva er formålet? Det bunner til syvende og sist ned i at vi lover hverande evig partnerskap, evig vennskap, og å for alltid være familie. Familie er der for hverandre, alltid. Uansett hva livet har å by på. Derfor var det ekstra vakkert å se alle menneskene vi er mest glad i her i verden samlet for å vitne at vi nå velger fremtiden sammen.',
  'Vi hadde en fantastisk bryllupsdag. Det var litt skummelt å følge med på det skiftende været i juni, vell vitende at vi har valgt å vie oss på en takterasse uten noe beskyttelse for regnet dersom det skulle komme. Heldigvis holdt regnet seg unna og vi hadde en fin sermoni med Ragnar fra Humnaistene.',
  'Vi ønsker å rette en stor takk til alle som valgte å komme i bryllupet vårt. Takk for alle bidrag. Kalandra som solist under vielsen trollbandt med nydelig norsk tolkning av Adele sin sang, Thorbjørn på gitar. Ingrid på valthorn, sang, og ikke minst tidenes ROAST av brudeparet. Vi gleder oss til hevn. hehe 😛 Per Kjetil, Ragnhild og Andreas i sang og taler. Det var veldig rørende og fine ord. Eva med egenkomponert sang, og Per på gitar og sang. Vi synes det er stas å høre på hvor talentfulle alle er, og vi er heldig som får ta del i deres musikalske verden. Alle talere: Bente og Trond, Lene og Jørn, Katrine, Stine, Silje og Sofie. Til slutt er det fortjent med stor applaus til våre toastmastere Stine og Martin som loset oss gjennom dagen, og var både prosjektledere, Toastmastere og tok seg av mye av det som skjedde i bakgrunenn slik at dagen ble vell gjennomført.',
  'Vi føler kjærligheten fra alle som har gledet seg med oss i forkant av dagen, og alle hyggelige tilbakemeldinger nå i etterkant. Vi ble gift, og nå gleder vi oss til å gi tilbake all den fantastiske støtten vi har fått i oppløpet til bryllupet.',
  'Vi har laget et bildegalleri med bilder fra dagen. Klikk på lenken i menyen på toppen og gjennopplev dagen gjennom kameralinsen!',
  'Alle bilder er tatt av Golden Productions.',
  'Sara og Øyvind ❤️',
]